version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000 # In the form of <Host Port>:<Container Port>
    volumes:
      - ./:/sample_api # Mount current directory on local to /sample_api in container
    restart: always
    